[package]
name = "linalg-traits-example"
version = "0.0.0"
authors = ["Tamas Kis"]
edition = "2024"
publish = false

[dependencies]
approx = "0.5.1"
faer-traits = "0.24.0"
linalg-traits = { path = "..", features = ["faer", "nalgebra", "ndarray"] }
nalgebra = "0.35.0"
num-traits = "0.2.19"
simba = "0.10.2"
